-- Migration: Add PDF enhancement settings
-- Run this in your Supabase SQL Editor

ALTER TABLE invoice_settings 
ADD COLUMN IF NOT EXISTS margin_top INTEGER NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS margin_right INTEGER NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS margin_bottom INTEGER NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS margin_left INTEGER NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS header_image_url TEXT,
ADD COLUMN IF NOT EXISTS show_header_image BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS footer_image_url TEXT,
ADD COLUMN IF NOT EXISTS show_footer_image BOOLEAN NOT NULL DEFAULT true;
